/**
 * @file exti.c
 * @brief This file contains the initialization and interrupt handler functions for external interrupt.
 * @author Yixiang Fan
 * @date 2024-08-01
 * @copyright Copyright 2024 Yixiang Fan. All rights reserved.
 */

#include "exti.h"
#include "led.h"
#include "SysTick.h"
#include "key.h"

/**
 * @brief Initializes external interrupt lines and NVIC.
 *
 * This function configures the GPIO pins for external interrupt lines, sets up the NVIC for the
 * corresponding EXTI interrupt channels, and initializes the EXTI registers. It enables the
 * specified GPIO pins as inputs with pull-up or pull-down resistors, and configures the EXTI
 * lines to trigger on rising or falling edges.
 *
 * @param void
 * @return void
 * @note This function should be called before using any external interrupt features in the application.
 * @warning Make sure to configure the GPIO pins and clocks properly before calling this function.
 */
void My_EXTI_Init(void) {
    NVIC_InitTypeDef NVIC_InitStructure;
    EXTI_InitTypeDef EXTI_InitStructure;

    RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);

    GPIO_EXTILineConfig(GPIO_PortSourceGPIOE, GPIO_PinSource2);  // Select GPIO pin for external interrupt line
    GPIO_EXTILineConfig(GPIO_PortSourceGPIOE, GPIO_PinSource3);  // Select GPIO pin for external interrupt line
    GPIO_EXTILineConfig(GPIO_PortSourceGPIOE, GPIO_PinSource4);  // Select GPIO pin for external interrupt line
    GPIO_EXTILineConfig(GPIO_PortSourceGPIOA, GPIO_PinSource0);  // Select GPIO pin for external interrupt line

    // EXTI0 NVIC configuration
    NVIC_InitStructure.NVIC_IRQChannel = EXTI0_IRQn;  // EXTI0 interrupt channel
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 2;  // Preemption priority
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 3;  // Subpriority
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;  // Enable IRQ channel
    NVIC_Init(&NVIC_InitStructure);  // Initialize VIC registers based on the specified parameters

    // EXTI2 NVIC configuration
    NVIC_InitStructure.NVIC_IRQChannel = EXTI2_IRQn;  // EXTI2 interrupt channel
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 2;  // Preemption priority
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 2;  // Subpriority
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;  // Enable IRQ channel
    NVIC_Init(&NVIC_InitStructure);  // Initialize VIC registers based on the specified parameters

    // EXTI3 NVIC configuration
    NVIC_InitStructure.NVIC_IRQChannel = EXTI3_IRQn;  // EXTI3 interrupt channel
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 2;  // Preemption priority
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 1;  // Subpriority
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;  // Enable IRQ channel
    NVIC_Init(&NVIC_InitStructure);  // Initialize VIC registers based on the specified parameters

    // EXTI4 NVIC configuration
    NVIC_InitStructure.NVIC_IRQChannel = EXTI4_IRQn;  // EXTI4 interrupt channel
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 2;  // Preemption priority
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;  // Subpriority
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;  // Enable IRQ channel
    NVIC_Init(&NVIC_InitStructure);  // Initialize VIC registers based on the specified parameters

    EXTI_InitStructure.EXTI_Line = EXTI_Line0;
    EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
    EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
    EXTI_InitStructure.EXTI_LineCmd = ENABLE;
    EXTI_Init(&EXTI_InitStructure);

    EXTI_InitStructure.EXTI_Line = EXTI_Line2 | EXTI_Line3 | EXTI_Line4;
    EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
    EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Falling;
    EXTI_InitStructure.EXTI_LineCmd = ENABLE;
    EXTI_Init(&EXTI_InitStructure);
}

/**
 * @brief Interrupt handler for EXTI0 line.
 *
 * This function handles the interrupt generated by the EXTI0 line. It checks if the interrupt
 * flag is set, waits for 10 milliseconds to debounce the button, and toggles LED2 if the button
 * is pressed.
 *
 * @param void
 * @return void
 */
void EXTI0_IRQHandler(void) {
    if (EXTI_GetITStatus(EXTI_Line0) == 1) {
        delay_ms(10);
        if (K_UP == 1) {
            led2 = 0;
        }
    }
    EXTI_ClearITPendingBit(EXTI_Line0);
}

/**
 * @brief Interrupt handler for EXTI3 line.
 *
 * This function handles the interrupt generated by the EXTI3 line. It checks if the interrupt
 * flag is set, waits for 10 milliseconds to debounce the button, and toggles LED2 if the button
 * is pressed.
 *
 * @param void
 * @return void
 */
void EXTI3_IRQHandler(void) {
    if (EXTI_GetITStatus(EXTI_Line3) == 1) {
        delay_ms(10);
        if (K_DOWN == 0) {
            led2 = 1;
        }
    }
    EXTI_ClearITPendingBit(EXTI_Line3);
}

/**
 * @brief Interrupt handler for EXTI2 line.
 *
 * This function handles the interrupt generated by the EXTI2 line. It checks if the interrupt
 * flag is set, waits for 10 milliseconds to debounce the button, and toggles LED3 if the button
 * is pressed.
 *
 * @param void
 * @return void
 */
void EXTI2_IRQHandler(void) {
    if (EXTI_GetITStatus(EXTI_Line2) == 1) {
        delay_ms(10);
        if (K_LEFT == 0) {
            led3 = 1;
        }
    }
    EXTI_ClearITPendingBit(EXTI_Line2);
}

/**
 * @brief Interrupt handler for EXTI4 line.
 *
 * This function handles the interrupt generated by the EXTI4 line. It checks if the interrupt
 * flag is set, waits for 10 milliseconds to debounce the button, and toggles LED3 if the button
 * is pressed.
 *
 * @param void
 * @return void
 */
void EXTI4_IRQHandler(void) {
    if (EXTI_GetITStatus(EXTI_Line4) == 1) {
        delay_ms(10);
        if (K_RIGHT == 0) {
            led3 = 0;
        }
    }
    EXTI_ClearITPendingBit(EXTI_Line4);
}
